use crate::champions::champion::{Champion, Gender, Species, Position, Resource, RangeType, Region};

pub fn get_champions() -> Vec<Champion> {
vec![
    Champion {
        name: "Aatrox".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Top],
        species: vec![Species::Darkin],
        resource: Resource::Manaless,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Runeterra, Region::Shurima],
        release_year: 2013,
        icon_path: "/icons/Aatrox.png".to_string(),
    },
    Champion {
        name: "Ahri".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle],
        species: vec![Species::Vastayan],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Ionia],
        release_year: 2011,
        icon_path: "/icons/Ahri.png".to_string(),
    },
    Champion {
        name: "Akali".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle],
        species: vec![Species::Human],
        resource: Resource::Energy,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Ionia],
        release_year: 2010,
        icon_path: "/icons/Akali.png".to_string(),
    },
    Champion {
        name: "Akshan".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Shurima],
        release_year: 2021,
        icon_path: "/icons/Akshan.png".to_string(),
    },
    Champion {
        name: "Alistar".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Support],
        species: vec![Species::Minotaur],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Runeterra, Region::Noxus],
        release_year: 2009,
        icon_path: "/icons/Alistar.png".to_string(),
    },
    Champion {
        name: "Ambessa Medarda".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Top],
        species: vec![Species::Human],
        resource: Resource::Energy,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Noxus],
        release_year: 2024,
        icon_path: "/icons/Ambessa.png".to_string(),
    },
    Champion {
        name: "Amumu".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle],
        species: vec![Species::Yordle, Species::Undead],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Shurima],
        release_year: 2009,
        icon_path: "/icons/Amumu.png".to_string(),
    },
    Champion {
        name: "Anivia".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle],
        species: vec![Species::God, Species::Spirit],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Freljord],
        release_year: 2009,
        icon_path: "/icons/Anivia.png".to_string(),
    },
    Champion {
        name: "Annie".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle],
        species: vec![Species::Human, Species::Magicborn],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Noxus],
        release_year: 2009,
        icon_path: "/icons/Annie.png".to_string(),
    },
    Champion {
        name: "Aphelios".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Bottom],
        species: vec![Species::Human, Species::Spiritualist],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Targon],
        release_year: 2019,
        icon_path: "/icons/Aphelios.png".to_string(),
    },
    Champion {
        name: "Ashe".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Bottom],
        species: vec![Species::Human, Species::Iceborn],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Freljord],
        release_year: 2009,
        icon_path: "/icons/Ashe.png".to_string(),
    },
    Champion {
        name: "Aurelion Sol".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::Celestial, Species::Dragon],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Targon, Region::Runeterra],
        release_year: 2016,
        icon_path: "/icons/AurelionSol.png".to_string(),
    },
    Champion {
        name: "Aurora".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle],
        species: vec![Species::Vastayan],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Freljord],
        release_year: 2024,
        icon_path: "/icons/Aurora.png".to_string(),
    },
    Champion {
        name: "Azir".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::GodWarrior],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Shurima],
        release_year: 2014,
        icon_path: "/icons/Azir.png".to_string(),
    },
        Champion {
        name: "Bard".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Support],
        species: vec![Species::Celestial],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Runeterra],
        release_year: 2015,
        icon_path: "/icons/Bard.png".to_string(),
    },
            Champion {
        name: "Bel'Veth".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle],
        species: vec![Species::VoidBeing],
        resource: Resource::Manaless,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Void],
        release_year: 2022,
        icon_path: "/icons/Belveth.png".to_string(),
    },
                Champion {
        name: "Blitzcrank".to_string(),
        gender: Gender::Other,
        positions: vec![Position::Support],
        species: vec![Species::Golem],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Zuan],
        release_year: 2009,
        icon_path: "/icons/Blitzcrank.png".to_string(),
    },
    Champion {
        name: "Brand".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Support],
        species: vec![Species::Human,Species::MagicallyAltered],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Freljord,Region::Runeterra],
        release_year: 2011,
        icon_path: "/icons/Brand.png".to_string(),
    },
        Champion {
        name: "Braum".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Support],
        species: vec![Species::Iceborn,Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Freljord],
        release_year: 2014,
        icon_path: "/icons/Braum.png".to_string(),
    },
    Champion {
        name: "Briar".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle],
        species: vec![Species::Golem],
        resource: Resource::Health,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Noxus],
        release_year: 2023,
        icon_path: "/icons/Briar.png".to_string(),
    },
        Champion {
        name: "Caitlyn".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Bottom],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Piltover],
        release_year: 2011,
        icon_path: "/icons/Caitlyn.png".to_string(),
    },
            Champion {
        name: "Camille".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Top],
        species: vec![Species::Cyborg, Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Piltover],
        release_year: 2016,
        icon_path: "/icons/Camille.png".to_string(),
    },
                Champion {
        name: "Cassiopeia".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle , Position::Top],
        species: vec![Species::Human, Species::MagicallyAltered],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Noxus , Region::Shurima],
        release_year: 2010,
        icon_path: "/icons/Cassiopeia.png".to_string(),
    },
                    Champion {
        name: "Cho'Gath".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle , Position::Top],
        species: vec![Species::VoidBeing],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Void],
        release_year: 2009,
        icon_path: "/icons/Chogath.png".to_string(),
    },
                        Champion {
        name: "Corki".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Bottom , Position::Middle],
        species: vec![Species::Yordle],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::BandleCity, Region::Piltover],
        release_year: 2009,
        icon_path: "/icons/Corki.png".to_string(),
    },
                            Champion {
        name: "Darius".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle , Position::Top],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Noxus],
        release_year: 2012,
        icon_path: "/icons/Darius.png".to_string(),
    },
                                Champion {
        name: "Diana".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle , Position::Middle],
        species: vec![Species::Aspect, Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Targon],
        release_year: 2012,
        icon_path: "/icons/Diana.png".to_string(),
    },
                                    Champion {
        name: "Dr.Mundo".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Top],
        species: vec![Species::ChemicallyAltered, Species::Human],
        resource: Resource::Health,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Zuan],
        release_year: 2009,
        icon_path: "/icons/DrMundo.png".to_string(),
    },
                                        Champion {
        name: "Draven".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Bottom],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Noxus],
        release_year: 2012,
        icon_path: "/icons/Draven.png".to_string(),
    },
                                            Champion {
        name: "Ekko".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle, Position::Middle],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Zuan],
        release_year: 2015,
        icon_path: "/icons/Ekko.png".to_string(),
    },
    Champion {
        name: "Elise".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle],
        species: vec![Species::Human, Species::MagicallyAltered],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee, RangeType::Ranged],
        regions: vec![Region::Noxus , Region::ShadowIsles],
        release_year: 2015,
        icon_path: "/icons/Elise.png".to_string(),
    },
        Champion {
        name: "Evelynn".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle],
        species: vec![Species::Demon, Species::Spirit],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Runeterra],
        release_year: 2009,
        icon_path: "/icons/Evelynn.png".to_string(),
    },
            Champion {
        name: "Ezreal".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Bottom],
        species: vec![Species::Human, Species::Magicborn],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Piltover],
        release_year: 2010,
        icon_path: "/icons/Ezreal.png".to_string(),
    },
                Champion {
        name: "Fiddlesticks".to_string(),
        gender: Gender::Other,
        positions: vec![Position::Jungle, Position::Support],
        species: vec![Species::Demon, Species::Spirit],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged],
        regions: vec![Region::Runeterra],
        release_year: 2009,
        icon_path: "/icons/Fiddlesticks.png".to_string(),
    },
    Champion {
        name: "Fiora".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Top],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Runeterra],
        release_year: 2012,
        icon_path: "/icons/Fiora.png".to_string(),
    },
        Champion {
        name: "Fizz".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::Yordle],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Bilgewater],
        release_year: 2011,
        icon_path: "/icons/Fizz.png".to_string(),
    },
    Champion {
        name: "Galio".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::Golem],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Demacia],
        release_year: 2010,
        icon_path: "/icons/Galio.png".to_string(),
    },
    Champion {
        name: "Gangplank".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Top],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Bilgewater],
        release_year: 2009,
        icon_path: "/icons/Gangplank.png".to_string(),
    },
    Champion {
        name: "Garen".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Top],
        species: vec![Species::Human],
        resource: Resource::Manaless,
        range_type: vec![RangeType::Melee],
        regions: vec![Region::Demacia],
        release_year: 2010,
        icon_path: "/icons/Garen.png".to_string(),
    },
        Champion {
        name: "Gnar".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Top],
        species: vec![Species::Yordle],
        resource: Resource::Rage,
        range_type: vec![RangeType::Melee, RangeType::Ranged] ,
        regions: vec![Region::Freljord],
        release_year: 2014,
        icon_path: "/icons/Gnar.png".to_string(),
    },
    Champion {
        name: "Gragas".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle, Position::Top],
        species: vec![Species::Human , Species::Iceborn],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Freljord],
        release_year: 2010,
        icon_path: "/icons/Gragas.png".to_string(),
    },
    Champion {
        name: "Graves".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Bilgewater],
        release_year: 2011,
        icon_path: "/icons/Graves.png".to_string(),
    },
        Champion {
        name: "Gwen".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Jungle, Position::Top],
        species: vec![Species::Human , Species::MagicallyAltered],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Camavor, Region::ShadowIsles],
        release_year: 2021,
        icon_path: "/icons/Gwen.png".to_string(),
    },
        Champion {
        name: "Hwei".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle],
        species: vec![Species::Human , Species::Magicborn],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Ionia],
        release_year: 2023,
        icon_path: "/icons/Hwei.png".to_string(),
    },
    Champion {
        name: "Heimerdinger".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle , Position::Top],
        species: vec![Species::Yordle],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Piltover],
        release_year: 2009,
        icon_path: "/icons/Heimerdinger.png".to_string(),
    },
        Champion {
        name: "Hecarim".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle],
        species: vec![Species::Undead],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Camavor, Region::ShadowIsles],
        release_year: 2012,
        icon_path: "/icons/Hecarim.png".to_string(),
    },
        Champion {
        name: "Illaoi".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Top],
        species: vec![Species::Human , Species::Spiritualist],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Bilgewater],
        release_year: 2015,
        icon_path: "/icons/Illaoi.png".to_string(),
    },
    Champion {
        name: "Irelia".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Middle, Position::Top],
        species: vec![Species::Human , Species::Spiritualist],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Ionia],
        release_year: 2010,
        icon_path: "/icons/Irelia.png".to_string(),
    },
        Champion {
        name: "Ivern".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle],
        species: vec![Species::Human , Species::MagicallyAltered],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Freljord, Region::Ionia],
        release_year: 2016,
        icon_path: "/icons/Ivern.png".to_string(),
    },
            Champion {
        name: "Janna".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Support],
        species: vec![Species::God , Species::Spirit],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Shurima, Region::Zuan],
        release_year: 2009,
        icon_path: "/icons/Janna.png".to_string(),
    },
    Champion {
        name: "Jarvan IV".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle],
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Demacia],
        release_year: 2011,
        icon_path: "/icons/JarvanIV.png".to_string(),
    },
        Champion {
        name: "Jax".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Jungle, Position::Top] ,
        species: vec![Species::Unknown],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee] ,
        regions: vec![Region::Icathia, Region::Runeterra, Region::Shurima],
        release_year: 2009,
        icon_path: "/icons/Jax.png".to_string(),
    },
            Champion {
        name: "Jayce".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Middle] ,
        species: vec![Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Melee, RangeType::Ranged] ,
        regions: vec![Region::Piltover],
        release_year: 2012,
        icon_path: "/icons/Jayce.png".to_string(),
    },
    Champion {
        name: "Jhin".to_string(),
        gender: Gender::Male,
        positions: vec![Position::Bottom] ,
        species: vec![Species::Human , Species::Spiritualist],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Ionia],
        release_year: 2016,
        icon_path: "/icons/Jhin.png".to_string(),
    },
        Champion {
        name: "Jinx".to_string(),
        gender: Gender::Female,
        positions: vec![Position::Bottom] ,
        species: vec![Species::ChemicallyAltered , Species::Human],
        resource: Resource::Mana,
        range_type: vec![RangeType::Ranged] ,
        regions: vec![Region::Zuan],
        release_year: 2013,
        icon_path: "/icons/Jinx.png".to_string(),
    },
    Champion {
    name: "Kai'Sa".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Bottom],
    species: vec![Species::Human, Species::VoidBeing],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Shurima, Region::Void],
    release_year: 2018,
    icon_path: "/icons/Kaisa.png".to_string(),
    },
    Champion {
    name: "Kalista".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Bottom],
    species: vec![Species::Undead],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::ShadowIsles, Region::Camavor],
    release_year: 2014,
    icon_path: "/icons/Kalista.png".to_string(),
    },
    Champion {
    name: "Karma".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Support],
    species: vec![Species::Human, Species::Spiritualist],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Ionia],
    release_year: 2009,
    icon_path: "/icons/Karma.png".to_string(),
},
Champion {
    name: "Karthus".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Undead],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Noxus, Region::ShadowIsles],
    release_year: 2009,
    icon_path: "/icons/Karthus.png".to_string(),
},
Champion {
    name: "Kassadin".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Human, Species::VoidBeing],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima, Region::Void],
    release_year: 2009,
    icon_path: "/icons/Kassadin.png".to_string(),
},
Champion {
    name: "Katarina".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Human],
    resource: Resource::Manaless,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Noxus],
    release_year: 2009,
    icon_path: "/icons/Katarina.png".to_string(),
},
Champion {
    name: "Kayle".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Top],
    species: vec![Species::Aspect, Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged, RangeType::Melee],
    regions: vec![Region::Demacia, Region::Targon],
    release_year: 2009,
    icon_path: "/icons/Kayle.png".to_string(),
},
Champion {
    name: "Kayn".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Darkin, Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia, Region::Noxus, Region::Runeterra, Region::Shurima],
    release_year: 2017,
    icon_path: "/icons/Kayn.png".to_string(),
},
Champion {
    name: "LeBlanc".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Noxus],
    release_year: 2010,
    icon_path: "/icons/Leblanc.png".to_string(),
},
Champion {
    name: "Lee Sin".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Human, Species::Spiritualist],
    resource: Resource::Energy,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia],
    release_year: 2011,
    icon_path: "/icons/LeeSin.png".to_string(),
},
Champion {
    name: "Leona".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Support],
    species: vec![Species::Aspect, Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Targon],
    release_year: 2011,
    icon_path: "/icons/Leona.png".to_string(),
},
Champion {
    name: "Lillia".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Jungle],
    species: vec![Species::Spirit],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia],
    release_year: 2011,
    icon_path: "/icons/Lillia.png".to_string(),
},
Champion {
    name: "Lissandra".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Human, Species::Iceborn],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Freljord],
    release_year: 2013,
    icon_path: "/icons/Lissandra.png".to_string(),
},
Champion {
    name: "Lucian".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Bottom],
    species: vec![Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Demacia, Region::ShadowIsles],
    release_year: 2013,
    icon_path: "/icons/Lucian.png".to_string(),
},
Champion {
    name: "Lulu".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Support],
    species: vec![Species::Yordle],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::BandleCity],
    release_year: 2012,
    icon_path: "/icons/Lulu.png".to_string(),
},
Champion {
    name: "Lux".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle, Position::Support],
    species: vec![Species::Human, Species::Spiritualist],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Demacia],
    release_year: 2010,
    icon_path: "/icons/Lux.png".to_string(),
},
Champion {
    name: "Malphite".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::Golem],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ixtal, Region::Shurima],
    release_year: 2009,
    icon_path: "/icons/Malphite.png".to_string(),
},
Champion {
    name: "Malzahar".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Middle],
    species: vec![Species::Human, Species::VoidBeing],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Shurima, Region::Void],
    release_year: 2010,
    icon_path: "/icons/Malzahar.png".to_string(),
},
Champion {
    name: "Master Yi".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Human, Species::Spiritualist],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia],
    release_year: 2009,
    icon_path: "/icons/MasterYi.png".to_string(),
},
Champion {
    name: "Mel".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle, Position::Support],
    species: vec![Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Noxus, Region::Piltover],
    release_year: 2025,
    icon_path: "/icons/Mel.png".to_string(),
},
Champion {
    name: "Milio".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Support],
    species: vec![Species::Human, Species::Magicborn],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Ixtal],
    release_year: 2023,
    icon_path: "/icons/Milio.png".to_string(),
},
Champion {
    name: "Miss Fortune".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Bottom],
    species: vec![Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Bilgewater],
    release_year: 2010,
    icon_path: "/icons/MissFortune.png".to_string(),
},
Champion {
    name: "Mordekaiser".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::Revenant],
    resource: Resource::Shield,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Noxus],
    release_year: 2010,
    icon_path: "/icons/Mordekaiser.png".to_string(),
},
Champion {
    name: "Morgana".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Support],
    species: vec![Species::Aspect, Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Demacia, Region::Targon],
    release_year: 2009,
    icon_path: "/icons/Morgana.png".to_string(),
},
Champion {
    name: "Naafiri".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Jungle, Position::Middle],
    species: vec![Species::Darkin, Species::Dog],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima],
    release_year: 2023,
    icon_path: "/icons/Naafiri.png".to_string(),
},
Champion {
    name: "Nami".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Support],
    species: vec![Species::Vastayan],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Bilgewater, Region::Runeterra],
    release_year: 2012,
    icon_path: "/icons/Nami.png".to_string(),
},
Champion {
    name: "Nami".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::GodWarrior],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima],
    release_year: 2009,
    icon_path: "/icons/Nami.png".to_string(),
},
Champion {
    name: "Nautilus".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Support],
    species: vec![Species::Revenant],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Bilgewater],
    release_year: 2012,
    icon_path: "/icons/Nautilus.png".to_string(),
},
Champion {
    name: "Neeko".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle, Position::Support],
    species: vec![Species::Vastayan],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Ixtal],
    release_year: 2018,
    icon_path: "/icons/Neeko.png".to_string(),
},
Champion {
    name: "Nidalee".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Jungle],
    species: vec![Species::Human, Species::Spiritualist],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged, RangeType::Melee],
    regions: vec![Region::Ixtal],
    release_year: 2009,
    icon_path: "/icons/Nidalee.png".to_string(),
},
Champion {
    name: "Nilah".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Bottom],
    species: vec![Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Bilgewater],
    release_year: 2022,
    icon_path: "/icons/Nilah.png".to_string(),
},
Champion {
    name: "Nocturne".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Demon, Species::Spirit],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Runeterra],
    release_year: 2011,
    icon_path: "/icons/Nocturne.png".to_string(),
},
Champion {
    name: "Nunu & Willump".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Human, Species::Yeti],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Freljord],
    release_year: 2009,
    icon_path: "/icons/Nunu.png".to_string(),
},
Champion {
    name: "Olaf".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::Human, Species::Iceborn],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Freljord],
    release_year: 2010,
    icon_path: "/icons/Olaf.png".to_string(),
},
Champion {
    name: "Orianna".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Golem],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Piltover],
    release_year: 2011,
    icon_path: "/icons/Orianna.png".to_string(),
},
Champion {
    name: "Ornn".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::God, Species::Spirit],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Freljord],
    release_year: 2017,
    icon_path: "/icons/Ornn.png".to_string(),
},
Champion {
    name: "Pantheon".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top, Position::Jungle , Position::Support],
    species: vec![Species::Aspect, Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Targon],
    release_year: 2010,
    icon_path: "/icons/Pantheon.png".to_string(),
},
Champion {
    name: "Poppy".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Top, Position::Jungle, Position::Support],
    species: vec![Species::Yordle],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Demacia],
    release_year: 2010,
    icon_path: "/icons/Poppy.png".to_string(),
},
Champion {
    name: "Pyke".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Support],
    species: vec![Species::Revenant],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Bilgewater],
    release_year: 2018,
    icon_path: "/icons/Pyke.png".to_string(),
},
Champion {
    name: "Qiyana".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Middle],
    species: vec![Species::Human, Species::Magicborn],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ixtal],
    release_year: 2019,
    icon_path: "/icons/Qiyana.png".to_string(),
},
Champion {
    name: "Quinn".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Top, Position::Middle],
    species: vec![Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Demacia],
    release_year: 2013,
    icon_path: "/icons/Quinn.png".to_string(),
},
Champion {
    name: "Rakan".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Support],
    species: vec![Species::Vastayan],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia],
    release_year: 2017,
    icon_path: "/icons/Rakan.png".to_string(),
},
Champion {
    name: "Rammus".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Unknown],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima],
    release_year: 2009,
    icon_path: "/icons/Rammus.png".to_string(),
},
Champion {
    name: "Rek'Sai".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Jungle],
    species: vec![Species::VoidBeing],
    resource: Resource::Rage,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima, Region::Void],
    release_year: 2014,
    icon_path: "/icons/RekSai.png".to_string(),
},
Champion {
    name: "Rell".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Jungle],
    species: vec![Species::Human, Species::MagicallyAltered, Species::Magicborn],
    resource: Resource::Mana,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Noxus],
    release_year: 2020,
    icon_path: "/icons/Rell.png".to_string(),
},
Champion {
    name: "Renata Glasc".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Support],
    species: vec![Species::ChemicallyAltered, Species::Human],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Zuan],
    release_year: 2022,
    icon_path: "/icons/Renata.png".to_string(),
},
Champion {
    name: "Renekton".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::GodWarrior],
    resource: Resource::Fury,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Shurima],
    release_year: 2011,
    icon_path: "/icons/Renekton.png".to_string(),
},
Champion {
    name: "Rengar".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Jungle],
    species: vec![Species::Vastayan],
    resource: Resource::Ferocity,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ixtal, Region::Shurima],
    release_year: 2012,
    icon_path: "/icons/Rengar.png".to_string(),
},
Champion {
    name: "Riven".to_string(),
    gender: Gender::Female,
    positions: vec![Position::Top],
    species: vec![Species::Human],
    resource: Resource::Manaless,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::Ionia, Region::Noxus],
    release_year: 2011,
    icon_path: "/icons/Riven.png".to_string(),
},
Champion {
    name: "Rumble".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::Yordle],
    resource: Resource::Heat,
    range_type: vec![RangeType::Melee],
    regions: vec![Region::BandleCity],
    release_year: 2011,
    icon_path: "/icons/Rumble.png".to_string(),
},
Champion {
    name: "Ryze".to_string(),
    gender: Gender::Male,
    positions: vec![Position::Top],
    species: vec![Species::Human, Species::MagicallyAltered],
    resource: Resource::Mana,
    range_type: vec![RangeType::Ranged],
    regions: vec![Region::Runeterra],
    release_year: 2009,
    icon_path: "/icons/Ryze.png".to_string(),
},
]

}
